package growae:core-pure;

world tx-codec {
  export encode-transfer: func(sender: list<u8>, recipient: list<u8>, amount: u64, nonce: u64) -> list<u8>;
  export decode-transfer-length: func(encoded: list<u8>) -> u32;
}
