services:
  aeternity-node:
    image: aeternity/aeternity:v7.2.0
    hostname: node
    ports:
      - '${AE_NODE_PORT:-3013}:3013'
      - '${AE_INTERNAL_PORT:-3113}:3113'
      - '${AE_CHANNEL_PORT:-3014}:3014'
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    volumes:
      - ./test/config/aeternity.yaml:/home/aeternity/aeternity.yaml
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3013/v3/status']
      interval: 5s
      timeout: 3s
      retries: 20
