////////////////////////////////////////////////////////////////////////////////
// Context
////////////////////////////////////////////////////////////////////////////////

export {
  ReactiveContext,
  ReactiveProvider,
  type ReactiveProviderProps,
} from '../context'

////////////////////////////////////////////////////////////////////////////////
// Errors
////////////////////////////////////////////////////////////////////////////////

export { BaseError, type BaseErrorType } from '../errors/base'
export {
  ReactiveProviderNotFoundError,
  type ReactiveProviderNotFoundErrorType,
} from '../errors/context'

////////////////////////////////////////////////////////////////////////////////
// Hydrate
////////////////////////////////////////////////////////////////////////////////

export {
  Hydrate,
  type HydrateProps,
} from '../hydrate'

////////////////////////////////////////////////////////////////////////////////
// Primitives
////////////////////////////////////////////////////////////////////////////////

export {
  type UseAccountParameters,
  type UseAccountReturnType,
  type UseActiveAccountParameters,
  type UseActiveAccountReturnType,
  type UseBalanceParameters,
  type UseBalanceReturnType,
  type UseBlockParameters,
  type UseBlockReturnType,
  type UseBuildTransactionParameters,
  type UseBuildTransactionReturnType,
  type UseCallContractParameters,
  type UseCallContractReturnType,
  type UseChannelDepositParameters,
  type UseChannelDepositReturnType,
  type UseClaimNameParameters,
  type UseClaimNameReturnType,
  type UseCloseChannelParameters,
  type UseCloseChannelReturnType,
  type UseCompileContractParameters,
  type UseCompileContractReturnType,
  type UseConfigParameters,
  type UseConfigReturnType,
  type UseConnectionParameters,
  type UseConnectionReturnType,
  type UseConnectionsParameters,
  type UseConnectionsReturnType,
  type UseConnectorClientParameters,
  type UseConnectorClientReturnType,
  type UseConnectorsParameters,
  type UseConnectorsReturnType,
  type UseConnectParameters,
  type UseConnectReturnType,
  type UseContractBytecodeParameters,
  type UseContractBytecodeReturnType,
  type UseContractEventsParameters,
  type UseContractEventsReturnType,
  type UseDeployContractParameters,
  type UseDeployContractReturnType,
  type UseDisconnectParameters,
  type UseDisconnectReturnType,
  type UseEstimateGasParameters,
  type UseEstimateGasReturnType,
  type UseHeightParameters,
  type UseHeightReturnType,
  type UseMicroBlockParameters,
  type UseMicroBlockReturnType,
  type UseNameEntryParameters,
  type UseNameEntryReturnType,
  type UseNetworkIdParameters,
  type UseNetworkIdReturnType,
  type UseNetworksParameters,
  type UseNetworksReturnType,
  type UseNodeClientParameters,
  type UseNodeClientReturnType,
  type UseOpenChannelParameters,
  type UseOpenChannelReturnType,
  type UseOracleQueriesParameters,
  type UseOracleQueriesReturnType,
  type UseOracleStateParameters,
  type UseOracleStateReturnType,
  type UsePayForTransactionParameters,
  type UsePayForTransactionReturnType,
  type UsePreclaimNameParameters,
  type UsePreclaimNameReturnType,
  type UseQueryOracleParameters,
  type UseQueryOracleReturnType,
  type UseReadContractParameters,
  type UseReadContractReturnType,
  type UseReadContractsParameters,
  type UseReadContractsReturnType,
  type UseReconnectParameters,
  type UseReconnectReturnType,
  type UseRegisterOracleParameters,
  type UseRegisterOracleReturnType,
  type UseResolveNameParameters,
  type UseResolveNameReturnType,
  type UseRespondToQueryParameters,
  type UseRespondToQueryReturnType,
  type UseRevokeNameParameters,
  type UseRevokeNameReturnType,
  type UseSendTransactionParameters,
  type UseSendTransactionReturnType,
  type UseSignDelegationParameters,
  type UseSignDelegationReturnType,
  type UseSignMessageParameters,
  type UseSignMessageReturnType,
  type UseSignTransactionParameters,
  type UseSignTransactionReturnType,
  type UseSignTypedDataParameters,
  type UseSignTypedDataReturnType,
  type UseSimulateContractParameters,
  type UseSimulateContractReturnType,
  type UseSpendParameters,
  type UseSpendReturnType,
  type UseSwitchActiveAccountParameters,
  type UseSwitchActiveAccountReturnType,
  type UseSwitchNetworkParameters,
  type UseSwitchNetworkReturnType,
  type UseTransactionCountParameters,
  type UseTransactionCountReturnType,
  type UseTransactionParameters,
  type UseTransactionReturnType,
  type UseTransferFundsParameters,
  type UseTransferFundsReturnType,
  type UseTransferNameParameters,
  type UseTransferNameReturnType,
  type UseUpdateNameParameters,
  type UseUpdateNameReturnType,
  type UseVerifyMessageParameters,
  type UseVerifyMessageReturnType,
  type UseVerifyTypedDataParameters,
  type UseVerifyTypedDataReturnType,
  type UseWaitForTransactionConfirmParameters,
  type UseWaitForTransactionConfirmReturnType,
  type UseWaitForTransactionParameters,
  type UseWaitForTransactionReturnType,
  type UseWatchConnectionParameters,
  type UseWatchConnectionReturnType,
  type UseWatchConnectorsParameters,
  type UseWatchConnectorsReturnType,
  type UseWatchHeightParameters,
  type UseWatchHeightReturnType,
  useAccount,
  useActiveAccount,
  // Chain reads
  useBalance,
  useBlock,
  useBuildTransaction,
  useCallContract,
  useChannelDeposit,
  useClaimName,
  useCloseChannel,
  useCompileContract,
  // Connection
  useConfig,
  useConnect,
  useConnection,
  useConnections,
  useConnectorClient,
  useConnectors,
  useContractBytecode,
  useContractEvents,
  // Contracts
  useDeployContract,
  useDisconnect,
  useEstimateGas,
  useHeight,
  useMicroBlock,
  useNameEntry,
  useNetworkId,
  useNetworks,
  useNodeClient,
  // Channels
  useOpenChannel,
  useOracleQueries,
  useOracleState,
  usePayForTransaction,
  // AENS
  usePreclaimName,
  useQueryOracle,
  useReadContract,
  useReadContracts,
  useReconnect,
  // Oracles
  useRegisterOracle,
  useResolveName,
  useRespondToQuery,
  useRevokeName,
  // Transactions
  useSendTransaction,
  useSignDelegation,
  // Signing
  useSignMessage,
  useSignTransaction,
  useSignTypedData,
  useSimulateContract,
  useSpend,
  useSwitchActiveAccount,
  useSwitchNetwork,
  useTransaction,
  useTransactionCount,
  useTransferFunds,
  useTransferName,
  useUpdateName,
  useVerifyMessage,
  useVerifyTypedData,
  useWaitForTransaction,
  useWaitForTransactionConfirm,
  useWatchConnection,
  useWatchConnectors,
  // Watchers
  useWatchHeight,
} from '../primitives/index'

////////////////////////////////////////////////////////////////////////////////
// @growae/reactive re-exports
////////////////////////////////////////////////////////////////////////////////

export type {
  Config,
  Connection,
  Connector,
  Network,
  State,
} from '@growae/reactive'
export {
  createConfig,
  createStorage,
  formatAmount,
  mainnet,
  testnet,
  toAe,
  toAettos,
} from '@growae/reactive'
