blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://reactive.growae.com
    about: Check the documentation before opening an issue
  - name: Aeternity Forum
    url: https://forum.aeternity.com
    about: For general Aeternity ecosystem questions
