// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_core`, `position`, `to_core`, `to_err`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`

/// The mainnet network id, for `signTransaction`/`verifyTransaction`.
String networkIdMainnet() =>
    RustLib.instance.api.crateApiCoreNetworkIdMainnet();

/// The public testnet's network id.
String networkIdTestnet() =>
    RustLib.instance.api.crateApiCoreNetworkIdTestnet();

/// Serialise a transaction to its `tx_` string, with explicit fee and gas
/// limit (this binding does not wrap a `FeeModel`; the caller supplies
/// `fee` and, for contract transactions, `gasLimit`).
String buildTx({required TxParams params}) =>
    RustLib.instance.api.crateApiCoreBuildTx(params: params);

/// Serialise a transaction to its RLP bytes — what gets hashed and signed.
Uint8List buildTxRlp({required TxParams params}) =>
    RustLib.instance.api.crateApiCoreBuildTxRlp(params: params);

/// Parse a `tx_` string back to its parameters.
TxParams unpackTx({required String encoded}) =>
    RustLib.instance.api.crateApiCoreUnpackTx(encoded: encoded);

/// Parse a `tx_` string, requiring it to carry `expected_tag`.
TxParams unpackTxAs({required String encoded, required Tag expectedTag}) =>
    RustLib.instance.api
        .crateApiCoreUnpackTxAs(encoded: encoded, expectedTag: expectedTag);

/// The `th_...` hash of a signed transaction, from its `tx_` string.
String transactionHash({required String encodedTx}) =>
    RustLib.instance.api.crateApiCoreTransactionHash(encodedTx: encodedTx);

/// The smallest fee, in aettos, `params` may carry.
///
/// Forwards `ae_core::fee::minimum_transaction_fee` — the joined entry point —
/// rather than hand-writing a `RebuildTx` bridge in this binding, same as
/// `bindings/python`. That matters beyond style: the ABI byte this prices a
/// `ContractCallTx` at comes off the wire `build_tx` will actually
/// serialise, not off whether the caller's `TxParams` happens to carry an
/// explicit `abiVersion`, and a bridge written per binding is exactly where
/// that distinction has gone missing before.
///
/// Returned as a decimal string: the minimum fee can exceed what fits in a
/// 64-bit int, and `flutter_rust_bridge` maps `u128` through a string rather
/// than Dart's `BigInt` by default across this boundary.
///
/// # Errors
///
/// - `gasLimit` absent on a contract transaction — no default is invented.
/// - An oracle ttl given as an absolute block height — convert it to a delta
///   first; this function does not look up the current height.
String minimumTransactionFee({required TxParams params}) =>
    RustLib.instance.api.crateApiCoreMinimumTransactionFee(params: params);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PublicKey>>
abstract class PublicKey implements RustOpaqueInterface {
  /// The `ak_...` address.
  String address();

  /// Parse an `ak_...` address.
  static PublicKey fromAddress({required String address}) =>
      RustLib.instance.api.crateApiCorePublicKeyFromAddress(address: address);

  /// Verify a detached signature over `message`.
  bool verify({required List<int> message, required Signature signature});

  /// Verify a signature over a transaction, given the network id it was
  /// signed for. Set `inner: true` for a signature taken over a
  /// `GaMetaTx`/`PayingForTx`-wrapped transaction.
  ///
  /// Accepts either payload a node accepts: the transaction's hash under
  /// the network id, which is what this library signs, and the
  /// transaction itself under the network id, which the node's own
  /// state-channel FSM signs. Both still carry the network id and the
  /// `inner` suffix, so a signature does not carry across a network or
  /// across the inner boundary. Signing is unaffected —
  /// `SecretKey.signTransaction` emits the hashed payload only.
  bool verifyTransaction(
      {required List<int> transaction,
      required String networkId,
      required Signature signature,
      required bool inner});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SecretKey>>
abstract class SecretKey implements RustOpaqueInterface {
  /// The account's `ak_...` address.
  String address();

  /// Parse an `sk_...` spelling.
  static SecretKey fromEncoded({required String input}) =>
      RustLib.instance.api.crateApiCoreSecretKeyFromEncoded(input: input);

  /// Build from a 32-byte seed.
  static SecretKey fromSeed({required U8Array32 seed}) =>
      RustLib.instance.api.crateApiCoreSecretKeyFromSeed(seed: seed);

  /// Generate a key from the operating system's randomness. For tests and
  /// for callers that hold their own keys — this crate never persists one.
  static SecretKey generate() =>
      RustLib.instance.api.crateApiCoreSecretKeyGenerate();

  /// The matching public key.
  PublicKey publicKey();

  /// Sign a human-readable message under the `aeternity Signed Message:`
  /// prefix.
  Signature signMessage({required String message});

  /// Sign a serialised transaction for `network_id`. Set `inner: true`
  /// when this transaction will be wrapped by a
  /// `GaMetaTx`/`PayingForTx` — the signature is not valid for the same
  /// transaction signed outer.
  Signature signTransaction(
      {required List<int> transaction,
      required String networkId,
      required bool inner});

  /// The `sk_...` spelling — the one way key material leaves this type.
  String toEncoded();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Signature>>
abstract class Signature implements RustOpaqueInterface {
  /// Parse an `sg_...` spelling.
  static Signature fromEncoded({required String input}) =>
      RustLib.instance.api.crateApiCoreSignatureFromEncoded(input: input);

  /// The raw 64 signature bytes.
  Uint8List toBytes();

  /// The `sg_...` spelling.
  String toEncoded();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TxParams>>
abstract class TxParams implements RustOpaqueInterface {
  /// Every field, by name, in schema order. `BTreeMap` does not round-trip
  /// through the FFI boundary for a map keyed on an opaque value type, so
  /// this is `(key, value)` pairs rather than a Dart `Map` — a caller who
  /// wants a map builds one from the pairs.
  List<(String, Value)> fields();

  /// Read a field.
  Value? get_({required String key});

  /// A new, empty parameter record for `tag` — the protocol's numeric tag
  /// (`12` for `SpendTx`, `42` for `ContractCreateTx`, and so on; see the
  /// `Tag` enum for the full, stable list) — at the tag's default version.
  factory TxParams({required Tag tag}) =>
      RustLib.instance.api.crateApiCoreTxParamsNew(tag: tag);

  /// Set a field.
  void set_({required String key, required Value value});

  /// Pin the serialised version instead of taking the tag's default.
  void setVersion({required int version});

  /// The transaction's tag.
  Tag tag();

  /// The pinned serialised version, if one was pinned.
  int? version();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Value>>
abstract class Value implements RustOpaqueInterface {
  /// This value as raw bytes, if it is `bytes`.
  Uint8List? asBytes();

  /// This value as an `xx_...` string, if it is `encoded`.
  String? asEncoded();

  /// This value as a plain string, if it is `text`.
  String? asText();

  /// This value as a nested transaction, if it is `tx`.
  TxParams? asTx();

  /// This value as a decimal string, if it is `uint`.
  String? asUintStr();

  /// Raw bytes with no encoding of their own: signatures, the `authFun`
  /// hash, pre-serialised state-tree entries.
  static Value bytes({required List<int> value}) =>
      RustLib.instance.api.crateApiCoreValueBytes(value: value);

  /// The `ctVersion` field: a VM version and an ABI version in one field.
  static Value ctVersion({required int vmVersion, required int abiVersion}) =>
      RustLib.instance.api.crateApiCoreValueCtVersion(
          vmVersion: vmVersion, abiVersion: abiVersion);

  /// Anything carrying an `xx_...` prefix: addresses, name ids, call data,
  /// state hashes, contract bytearrays.
  static Value encoded({required String value}) =>
      RustLib.instance.api.crateApiCoreValueEncoded(value: value);

  /// This value's shape: one of `uint`, `text`, `encoded`, `bytes`,
  /// `list`, `pointers`, `ct_version`, `tx`.
  String kind();

  /// A repeated field.
  static Value list({required List<Value> values}) =>
      RustLib.instance.api.crateApiCoreValueList(values: values);

  /// The `pointers` field of a `NameUpdateTx`, as `(key, id)` pairs — `id`
  /// is either an `xx_...` address or, from pointer version 2, a `ba_...`
  /// blob.
  static Value pointers({required List<(String, String)> pointers}) =>
      RustLib.instance.api.crateApiCoreValuePointers(pointers: pointers);

  /// A plain string field: an oracle format, a query, an AENS name.
  static Value text({required String value}) =>
      RustLib.instance.api.crateApiCoreValueText(value: value);

  /// A nested transaction: `SignedTx.encodedTx`, `GaMetaTx.tx`,
  /// `PayingForTx.tx`. Most callers want [`Value::encoded`] with the
  /// nested tx's `tx_...` string instead — that is what the reference SDK
  /// emits.
  ///
  /// Takes `params` by reference and clones it, rather than consuming it —
  /// the PyO3 binding's equivalent clones out of the Python wrapper
  /// implicitly (`from_py_object`), and a `TxParams` a caller built once
  /// to wrap into several sibling `GaMetaTx`/`PayingForTx` arms should
  /// stay usable after the first wrap, not be disposed by it.
  static Value tx({required TxParams params}) =>
      RustLib.instance.api.crateApiCoreValueTx(params: params);

  /// An unsigned integer field, from a value small enough for `u64`
  /// (amounts, nonces, TTLs, fees, gas).
  static Value uint({required BigInt value}) =>
      RustLib.instance.api.crateApiCoreValueUint(value: value);

  /// An unsigned integer field, from a decimal string — for values wider
  /// than `u64`.
  static Value uintStr({required String value}) =>
      RustLib.instance.api.crateApiCoreValueUintStr(value: value);
}

/// Every transaction tag the node serialises, with its on-chain numeric
/// value — mirrors `ae_core::tx::Tag` and, in shape, `ae_core.Tag` in the
/// Python binding. Kept in step with the Rust crate by hand, same as there:
/// the numbers are protocol constants and are not consecutive.
enum Tag {
  /// A transaction plus its signatures.
  signedTx,

  /// Transfer of AE between two accounts.
  spendTx,

  /// Register an oracle.
  oracleRegisterTx,

  /// Ask a registered oracle a question.
  oracleQueryTx,

  /// Answer an oracle query.
  oracleRespondTx,

  /// Extend an oracle's TTL.
  oracleExtendTx,

  /// Claim a preclaimed AENS name.
  nameClaimTx,

  /// Commit to claiming an AENS name.
  namePreclaimTx,

  /// Update an AENS name's pointers and TTLs.
  nameUpdateTx,

  /// Revoke an AENS name.
  nameRevokeTx,

  /// Transfer an AENS name to another account.
  nameTransferTx,

  /// Deploy a contract.
  contractCreateTx,

  /// Call a deployed contract.
  contractCallTx,

  /// Open a state channel.
  channelCreateTx,

  /// Deposit into a state channel.
  channelDepositTx,

  /// Withdraw from a state channel.
  channelWithdrawTx,

  /// Close a state channel with both parties' agreement.
  channelCloseMutualTx,

  /// Close a state channel unilaterally.
  channelCloseSoloTx,

  /// Punish a counterparty who closed on an outdated state.
  channelSlashTx,

  /// Settle a channel after the lock period.
  channelSettleTx,

  /// An off-chain channel state update.
  channelOffChainTx,

  /// Snapshot a channel's off-chain state on-chain.
  channelSnapshotSoloTx,

  /// Force a contract call on-chain inside a channel.
  channelForceProgressTx,

  /// Attach generalized-account authorisation to an account.
  gaAttachTx,

  /// A generalized-account meta transaction wrapping an inner transaction.
  gaMetaTx,

  /// Pay another account's transaction fee.
  payingForTx,
  ;

  /// The tag's on-chain numeric value, for a caller that wants to pin it
  /// down independently of this enum's Dart spelling.
  int asU32() => RustLib.instance.api.crateApiCoreTagAsU32(
        that: this,
      );

  /// Parse a numeric tag. Errors if the number is not one the node
  /// serialises.
  static Tag fromU32({required int value}) =>
      RustLib.instance.api.crateApiCoreTagFromU32(value: value);
}

class U8Array32 extends NonGrowableListView<int> {
  static const arraySize = 32;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array32(this._inner)
      : assert(_inner.length == arraySize),
        super(_inner);

  U8Array32.init() : this(Uint8List(arraySize));
}
