// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List> transform({required List<int> input}) =>
    RustLib.instance.api.crateApiTransform(input: input);

Future<Frame> decode({required List<int> input}) =>
    RustLib.instance.api.crateApiDecode(input: input);

enum DecodeError {
  tooShort,
  checksumMismatch,
  ;
}

class Frame {
  final int len;
  final int checksum;
  final Uint8List payload;

  const Frame({
    required this.len,
    required this.checksum,
    required this.payload,
  });

  @override
  int get hashCode => len.hashCode ^ checksum.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Frame &&
          runtimeType == other.runtimeType &&
          len == other.len &&
          checksum == other.checksum &&
          payload == other.payload;
}
