NETWORK_ID_MAINNET: str
NETWORK_ID_TESTNET: str

class Value:
    @staticmethod
    def uint(value: int) -> Value: ...
    @staticmethod
    def uint_str(value: str) -> Value: ...
    @staticmethod
    def text(value: str) -> Value: ...
    @staticmethod
    def encoded(value: str) -> Value: ...
    @staticmethod
    def bytes(value: bytes) -> Value: ...
    @staticmethod
    def list(values: list[Value]) -> Value: ...
    @staticmethod
    def pointers(pointers: list[tuple[str, str]]) -> Value: ...
    @staticmethod
    def ct_version(vm_version: int, abi_version: int) -> Value: ...
    @staticmethod
    def tx(params: TxParams) -> Value: ...
    def kind(self) -> str: ...
    def as_uint_str(self) -> str | None: ...
    def as_text(self) -> str | None: ...
    def as_encoded(self) -> str | None: ...
    def as_bytes(self) -> bytes | None: ...
    def as_tx(self) -> TxParams | None: ...

class TxParams:
    def __init__(self, tag: int) -> None: ...
    def set_version(self, version: int) -> None: ...
    def set(self, key: str, value: Value) -> None: ...
    @property
    def tag(self) -> int: ...
    @property
    def version(self) -> int | None: ...
    def get(self, key: str) -> Value | None: ...
    def fields(self) -> dict[str, Value]: ...

def build_tx(params: TxParams) -> str: ...
def build_tx_rlp(params: TxParams) -> bytes: ...
def unpack_tx(encoded: str) -> TxParams: ...
def unpack_tx_as(encoded: str, expected_tag: int) -> TxParams: ...
def transaction_hash(encoded_tx: str) -> str: ...

class PublicKey:
    @staticmethod
    def from_address(address: str) -> PublicKey: ...
    def address(self) -> str: ...
    def verify(self, message: bytes, signature: Signature) -> bool: ...
    def verify_transaction(
        self,
        transaction: bytes,
        network_id: str,
        signature: Signature,
        inner: bool = ...,
    ) -> bool: ...

class Signature:
    @staticmethod
    def from_encoded(input: str) -> Signature: ...
    def to_encoded(self) -> str: ...
    def to_bytes(self) -> bytes: ...

class SecretKey:
    @staticmethod
    def from_seed(seed: bytes) -> SecretKey: ...
    @staticmethod
    def generate() -> SecretKey: ...
    @staticmethod
    def from_encoded(input: str) -> SecretKey: ...
    def to_encoded(self) -> str: ...
    def public_key(self) -> PublicKey: ...
    def address(self) -> str: ...
    def sign_transaction(
        self, transaction: bytes, network_id: str, inner: bool = ...
    ) -> Signature: ...
    def sign_message(self, message: str) -> Signature: ...
