//! The matrix as a document a reviewer reads, rather than as json a gate parses.
//!
//! Both are emitted from the same computation, so they cannot disagree.

use std::fmt::Write as _;

use ae_core::entry::SdkCoverage;

use crate::matrix::Matrix;
use crate::scope::{Origin, Reach};

/// Render the matrix as markdown.
pub fn markdown(matrix: &Matrix) -> String {
    let mut out = String::new();
    let green = matrix
        .transactions
        .iter()
        .filter(|row| row.is_green())
        .count();

    let _ = writeln!(out, "# Parity matrix");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Generated by `cargo run -p ae-parity -- matrix`. Do not hand-edit — CI \
         regenerates this file and fails on any difference."
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "References: `@aeternity/aepp-sdk` {}, `@aeternity/aepp-calldata` {}.",
        matrix.references.aepp_sdk, matrix.references.aepp_calldata
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "## Summary");
    let _ = writeln!(out);
    let _ = writeln!(out, "| Surface | Covered | Of | Reference |");
    let _ = writeln!(out, "|---|---|---|---|");
    let _ = writeln!(
        out,
        "| Transaction schema entries | {green} | {} | `aepp-sdk` {} |",
        matrix.transactions.len(),
        matrix.references.aepp_sdk
    );
    let _ = writeln!(
        out,
        "| Transaction schema fields | {} | {} | — |",
        matrix.fields_exercised, matrix.fields_total
    );
    let _ = writeln!(
        out,
        "| State-tree entry pairs | {} | {} | **none committed** |",
        matrix.entries.iter().filter(|row| row.fixtures > 0).count(),
        matrix.entries.len()
    );
    let _ = writeln!(
        out,
        "| FATE vectors, decode and re-encode | {} | {} | `aepp-calldata` {} |",
        matrix.fate.roundtrip_pass, matrix.fate.vectors, matrix.references.aepp_calldata
    );
    let _ = writeln!(
        out,
        "| FATE value variants | {} | {} | `aepp-calldata` {} |",
        matrix.fate.value_variants_covered.len(),
        matrix.fate.value_variants_covered.len() + matrix.fate.value_variants_uncovered.len(),
        matrix.references.aepp_calldata
    );
    let _ = writeln!(
        out,
        "| FATE type variants | {} | {} | `aepp-calldata` {} |",
        matrix.fate.type_variants_covered.len(),
        matrix.fate.type_variants_covered.len() + matrix.fate.type_variants_uncovered.len(),
        matrix.references.aepp_calldata
    );
    let _ = writeln!(out);

    let _ = writeln!(out, "## Transactions");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "`reach` is how a consumer gets here: a named action, or only the generic \
         builder that takes any tag. `origin` is who serialises it in the flow \
         that runs — a node-built tag is proved by the round trip, not by the \
         build."
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "| Tag | v | Reach | Origin | Vectors | Postable | Build | Round trip | Fields not set | Fee fixed point |"
    );
    let _ = writeln!(out, "|---|---|---|---|---|---|---|---|---|---|");
    for row in &matrix.transactions {
        let reach = match row.reach {
            Reach::NamedAction => "action",
            Reach::PublicSurfaceOnly => "generic builder only",
        };
        let origin = match row.origin {
            Origin::ClientBuilt => "client",
            Origin::NodeBuilt => "node",
        };
        let build = mark(row.build_pass, row.vectors);
        let roundtrip = mark(row.roundtrip_pass, row.vectors);
        let unset = if row.unexercised_fields.is_empty() {
            "—".to_string()
        } else {
            format!(
                "{} ({})",
                row.unexercised_fields.len(),
                row.unexercised_fields.join(", ")
            )
        };
        let fee = if row.fee_fixed_point_unexercised {
            "**not exercised**"
        } else {
            "—"
        };
        let postable = if row.refusals.is_empty() {
            format!("{}", row.postable_vectors)
        } else {
            format!("**{}/{}**", row.postable_vectors, row.vectors)
        };
        let _ = writeln!(
            out,
            "| `{:?}` | {} | {reach} | {origin} | {} | {postable} | {build} | {roundtrip} | {unset} | {fee} |",
            row.tag, row.version, row.vectors
        );
    }
    let _ = writeln!(out);

    if !matrix.unexercised_codecs.is_empty() {
        let _ = writeln!(
            out,
            "**Field codecs no vector exercises:** {}.",
            matrix
                .unexercised_codecs
                .iter()
                .map(|codec| format!("`{codec}`"))
                .collect::<Vec<_>>()
                .join(", ")
        );
        let _ = writeln!(out);
    }

    let refusals: Vec<&crate::matrix::VectorRefusal> = matrix
        .transactions
        .iter()
        .flat_map(|row| row.refusals.iter())
        .collect();
    if !refusals.is_empty() {
        let _ = writeln!(
            out,
            "**Non-postable vectors.** Correct bytes, content a node refuses. Kept \
             as encoding tests, excluded from the on-node clause, and re-measured \
             on every on-node run — a marking nothing re-checks is a marking that \
             rots."
        );
        let _ = writeln!(out);
        for refusal in &refusals {
            let sibling = match &refusal.sibling {
                Some(sibling) => format!("postable sibling `{sibling}`"),
                None => "**no postable sibling — named exception**".to_string(),
            };
            let _ = writeln!(
                out,
                "- `{}` — `{}`, {sibling}. {}",
                refusal.vector, refusal.error_code, refusal.rule
            );
        }
        let _ = writeln!(out);
    }

    let failures: Vec<&String> = matrix
        .transactions
        .iter()
        .flat_map(|row| row.failures.iter())
        .collect();
    if failures.is_empty() {
        let _ = writeln!(out, "No transaction vector diverges from the reference.");
    } else {
        let _ = writeln!(out, "**Divergences:**");
        let _ = writeln!(out);
        for failure in failures {
            let _ = writeln!(out, "- {failure}");
        }
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## State-tree entries");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "No entry **fixture set** is committed anywhere in this repository, so \
         every row below is zero. Real entry bytes do exist here — the mined \
         corpus in `ae-core/tests/vectors/chain.json` carries `TreesPoi` inside \
         its channel transactions — but bytes nobody has decoded pair by pair \
         are not coverage, and extracting them is Core parity's row rather than \
         this crate's. The `reference` column says who could speak for the pair \
         if a fixture existed: two pairs the node emits and the reference sdk \
         does not implement, where the sdk is not an oracle and a node fixture \
         is the only honest source."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "| Entry | v | Reference | Fixtures |");
    let _ = writeln!(out, "|---|---|---|---|");
    for row in &matrix.entries {
        let reference = match row.sdk {
            SdkCoverage::Covered => "`aepp-sdk`",
            SdkCoverage::NodeOnly => "**node only**",
        };
        let _ = writeln!(
            out,
            "| `{}` | {} | {reference} | {} |",
            row.tag, row.version, row.fixtures
        );
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## FATE");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Every vector is decoded through `ae-fate` and re-encoded; the row counts \
         those that come back to the reference's exact bytes. Variant coverage is \
         read off what the corpus actually decodes to, including nested values, \
         not off the case names."
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "- vectors: {} decode and re-encode, {} total",
        matrix.fate.roundtrip_pass, matrix.fate.vectors
    );
    let _ = writeln!(
        out,
        "- value variants with no vector: {}",
        list_or_none(&matrix.fate.value_variants_uncovered)
    );
    let _ = writeln!(
        out,
        "- type variants with no vector: {}",
        list_or_none(&matrix.fate.type_variants_uncovered)
    );
    if !matrix.fate.failures.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(out, "**Divergences:**");
        let _ = writeln!(out);
        for failure in &matrix.fate.failures {
            let _ = writeln!(out, "- {failure}");
        }
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## On-node");
    let _ = writeln!(out);
    match &matrix.node {
        None => {
            let _ = writeln!(
                out,
                "Not merged into this run. The on-node half needs a reachable node \
                 and is therefore not part of the offline gate; see `TESTNET.md` \
                 for the recorded exercise and `node-exercise.mjs` to re-run it."
            );
        }
        Some(node) => {
            if let Some(clause) = &matrix.node_clause {
                let _ = writeln!(
                    out,
                    "Clause 6, scored over the **postable** set. A non-postable \
                     vector is excluded by construction — scoring it would make \
                     the clause unachievable by any corpus that documents a chain \
                     rule — and a named exception is carried rather than counted."
                );
                let _ = writeln!(out);
                let _ = writeln!(
                    out,
                    "**Clause 6: {}.**",
                    if clause.is_satisfied() {
                        "satisfied"
                    } else {
                        "NOT satisfied"
                    }
                );
                let _ = writeln!(out);
                let _ = writeln!(
                    out,
                    "- postable vectors accepted by the decoder: {} of {}",
                    clause.postable_accepted, clause.postable_total
                );
                let _ = writeln!(
                    out,
                    "- postable vectors refused: {}",
                    list_or_none(&clause.postable_rejected)
                );
                let _ = writeln!(
                    out,
                    "- stale markings — non-postable but the node took them: {}",
                    list_or_none(&clause.stale_markings)
                );
                let _ = writeln!(
                    out,
                    "- named exceptions, carried not counted: {}",
                    list_or_none(&clause.exceptions)
                );
                let _ = writeln!(
                    out,
                    "- node builder: {} identical, differs on {}",
                    clause.builder_identical,
                    list_or_none(&clause.builder_differs)
                );
                let _ = writeln!(
                    out,
                    "- corrupted controls all rejected: {}",
                    clause.controls_rejected
                );
                let _ = writeln!(
                    out,
                    "- node builder returned a different transaction, so nothing to \
                     compare: {}",
                    list_or_none(&clause.builder_not_comparable)
                );
                let _ = writeln!(
                    out,
                    "- name-update endpoint preserves pointer order: {}",
                    match clause.endpoint_preserves_pointer_order {
                        None => "not probed".to_string(),
                        Some(true) => "**yes — a standing exclusion has expired**".to_string(),
                        Some(false) => "no, re-measured this run".to_string(),
                    }
                );
                if !clause.excluded.is_empty() {
                    let _ = writeln!(out);
                    let _ = writeln!(out, "Excluded, each naming its rule:");
                    let _ = writeln!(out);
                    for excluded in &clause.excluded {
                        let _ = writeln!(out, "- {excluded}");
                    }
                }
                let _ = writeln!(out);
            }
            let _ = writeln!(out, "<details><summary>Raw run</summary>");
            let _ = writeln!(out);
            let _ = writeln!(out, "```json");
            let _ = writeln!(
                out,
                "{}",
                serde_json::to_string_pretty(node).unwrap_or_default()
            );
            let _ = writeln!(out, "```");
            let _ = writeln!(out);
            let _ = writeln!(out, "</details>");
        }
    }

    out
}

fn mark(pass: usize, total: usize) -> String {
    if total == 0 {
        "**no vector**".to_string()
    } else if pass == total {
        format!("{pass}/{total}")
    } else {
        format!("**{pass}/{total}**")
    }
}

fn list_or_none(items: &[String]) -> String {
    if items.is_empty() {
        "none".to_string()
    } else {
        items
            .iter()
            .map(|item| format!("`{item}`"))
            .collect::<Vec<_>>()
            .join(", ")
    }
}
